In [1]:
import numpy as np
import pandas as pd
import scipy
import matplotlib.pyplot as plt

from sklearn import preprocessing
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [2]:
data_uri = '/home/jmp/Data/toy_data/Ex_Files_Python_Data_Science_EssT_Pt2/Exercise Files/Data/mtcars.csv'
cars = pd.read_csv(data_uri)
cars.columns = ['car_names', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
X_prime = cars[['mpg', 'disp', 'hp', 'wt']].values
y = cars.am.values

In [3]:
X = preprocessing.scale(X_prime)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=17)

In [5]:
clf = KNeighborsClassifier()
clf.fit(X_train, y_train)
print(clf)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')


In [6]:
y_pred = clf.predict(X_test)
report = metrics.classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.80      1.00      0.89         4
           1       1.00      0.67      0.80         3

    accuracy                           0.86         7
   macro avg       0.90      0.83      0.84         7
weighted avg       0.89      0.86      0.85         7



In [7]:
metrics.roc_curve(y_test, y_pred)

(array([0., 0., 1.]),
 array([0.        , 0.66666667, 1.        ]),
 array([2, 1, 0]))